name: Build macOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build macOS artifacts
        run: npm run dist
        env:
          # Add these secrets in GitHub for code signing
          CSC_LINK: ${{ secrets.APPLE_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # Optional: for notarization
          # APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          # APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          # APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clipai-mac-dist
          path: dist/*
          if-no-files-found: error
